auto_sync = false
update_check = false
workspaces = true
filter_mode_shell_up_key_binding = "directory"
enter_accept = true

[stats]
## Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "apt",
  "cargo",
  "chezmoi",
  "composer",
  "distrobox",
  "dnf",
  "docker",
  "git",
  "go",
  "ip",
  "kubectl",
  "nix",
  "nmcli",
  "npm",
  "npx",
  "pecl",
  "pnpm",
  "podman",
  "port",
  "systemctl",
  "tmux",
  "yarn",
]

## Set commands that will be completely ignored from stats
ignored_commands = ["cd", "ls", "vi", "vim", "nvim", "nnvim", "nvim-nightly"]

[sync]
# Enable sync v2 by default
# This ensures that sync v2 is enabled for new installs only
# In a later release it will become the default across the board
records = true
