#!/bin/zsh
##? yazi wrapper that drops me in the cwd on exit

#function yy {
	local tmp=$(mktemp -p /tmp/yazi "yazi-cwd.XXXXXX")
  local cwd=${(f)$(< $1)}
	yazi "$@" --cwd-file="$tmp"
  
  if [[ -d $cwd && $cwd != $PWD ]]; then
    cd -- $cwd
	fi
#}
