#!/bin/zsh
##? yazi wrapper that drops me in the cwd on exit

#function yy {
	local tmp=$(mktemp -p /tmp/yazi "yazi-cwd.XXXXXX")
	command yazi "$@" --cwd-file="$tmp"

  local cwd=$(< $tmp)
  if [[ -d $cwd && $cwd != $PWD ]]; then
    cd -- $cwd
	fi
#}
