#!/bin/zsh
#
# .zstyles - Set zstyle settings for plugins that need them.
#

#
# Antidote
#

zstyle ':antidote:bundle' file ${ZDOTDIR:-~}/.zsh_plugins.txt
zstyle ':antidote:bundle' use-friendly-names 'yes'

# First insert the common substring
# all Tab widgets
zstyle ':autocomplete:*complete*:*' insert-unambiguous yes

# all history widgets
zstyle ':autocomplete:*history*:*' insert-unambiguous yes

# ^S
zstyle ':autocomplete:menu-search:*' insert-unambiguous yes
