#!/bin/zsh
#
# .aliases - Set whatever shell aliases you want.
#

# global aliases expand anywhere on the command line
alias -g -- -h='-h 2>&1 | bat --language=help --style=plain'
alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'

alias _=sudo

alias cat="bat"
alias curlie='curlie --curl'
alias cd..='cd ..'

alias nneovide="NEOVIM_BIN=$HOME/.local/bin/nvim-nightly neovide"
alias nnvim="nvim-nightly"

alias please=sudo

alias quit='exit'

alias vim="nvim"

alias zshrc='chezmoi edit "${ZDOTDIR:-$HOME}"/.zshrc'
alias zdot='cd ${ZDOTDIR:-~}'

