#!/bin/zsh
#
# .zshrc - Zsh file loaded on interactive shell sessions.
#

# Zsh options.
setopt extended_glob

## Nested shell awareness
YAZI_TERM=""
if [ -n "$YAZI_LEVEL" ]; then
  YAZI_TERM="|  Yazi terminal: "
fi
PS1="$PS1$YAZI_TERM"

# Autoload functions you might want to use with antidote.
ZFUNCDIR=${ZFUNCDIR:-$ZDOTDIR/functions}
fpath=($ZFUNCDIR $fpath)
autoload -Uz $fpath[1]/*(.:t)

# Set ZDOTDIR if you want to re-home Zsh.
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export ZDOTDIR=${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}

# npm stuff
export CHECKPOINT_DISABLE=1
export MISE_NODE_COREPACK=true

if [[ $CONTAINER_ID = "dev" ]]; then
  pathmunge $HOME/go/bin
  pathmunge $HOME/.cargo/bin
fi

pathmunge $HOME/devbox/bin
pathmunge $HOME/.local/bin

# Source zstyles you might use with antidote.
[[ -e ${ZDOTDIR:-~}/.zstyles ]] && source ${ZDOTDIR:-~}/.zstyles

# Clone antidote if necessary.
[[ -d ${ZDOTDIR:-~}/.antidote ]] ||
  git clone https://github.com/mattmc3/antidote ${ZDOTDIR:-~}/.antidote

# Create an amazing Zsh config using antidote plugins.
source ${ZDOTDIR:-~}/.antidote/antidote.zsh
# antidote load

### https://github.com/marlonrichert/zsh-autocomplete
# Make Tab and ShiftTab cycle completions on the command line
# bindkey              '^I'         menu-complete
# bindkey "$terminfo[kcbt]" reverse-menu-complete

# Make Enter always submit the command line
# bindkey -M menuselect '^M' .accept-line
###

### keybinds
bindkey '^P' atuin-up-search
###

source <(atuin init zsh)
source <(starship init zsh)
source <(zoxide init zsh --cmd cd)
