#!/bin/zsh
#
# .zshrc - Zsh file loaded on interactive shell sessions.
#

# Zsh options.
setopt extended_glob

## Nested shell awareness
YAZI_TERM=""
if [ -n "$YAZI_LEVEL" ]; then
  YAZI_TERM="|  Yazi terminal: "
fi
PS1="$PS1$YAZI_TERM"

# Autoload functions you might want to use with antidote.
ZFUNCDIR=${ZFUNCDIR:-$ZDOTDIR/functions}
fpath=($ZFUNCDIR $fpath)
autoload -Uz $fpath[1]/*(.:t)

[[ -e ${ZDOTDIR:-~}/.zstyles ]] && source ${ZDOTDIR:-~}/.zstyles

[[ -d ${ZDOTDIR:-~}/.antidote ]] ||
  git clone https://github.com/mattmc3/antidote ${ZDOTDIR:-~}/.antidote

source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote load

PATH=$HOME/.local/bin:$PATH

source <(devbox global shellenv)

DEVBOX_COREPACK_ENABLED=1

### https://github.com/marlonrichert/zsh-autocomplete
# Make Tab and ShiftTab cycle completions on the command line
# bindkey              '^I'         menu-complete
# bindkey "$terminfo[kcbt]" reverse-menu-complete

# Make Enter always submit the command line
# bindkey -M menuselect '^M' .accept-line
###

### keybinds
bindkey '^P' atuin-up-search
###

source <(atuin init zsh)
source <(starship init zsh)
source <(zoxide init zsh --cmd cd)
