#!/bin/zsh
#
# .aliases - Set whatever shell aliases you want.
#

# global aliases expand anywhere on the command line
alias -g -- -h='-h 2>&1 | bat --language=help --style=plain'
alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'
alias -g -- ls='eza'

alias _=sudo

alias cat="bat"
alias curlie='curlie --curl'
alias cd..='cd ..'

## `ls` -> `eza`
alias eza='eza -lbHo --smart-group --git --git-repos'
alias ld='eza -D'
alias lf='eza -af --color=always'
alias lh='eza -d .* --group-directories-first'
alias ll='eza -a --group-directories-first'
alias lt='eza -a --sort=modified'

alias please=sudo

alias rm="echo -e 'If you want to use rm really, then use \"\\\\rm\" instead.'; false"

alias quit='exit'

alias vim="nvim"

alias zshrc='chezmoi edit ${ZDOTDIR:-$HOME}/.zshrc'
alias zdot='cd ${ZDOTDIR:-~}'

