devbox = "$HOME/devbox"
dotfilesRepo = 'git@github.com:redbeardymcgee/dotfiles.git'
chezmoiInitHook = 'sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "{{ .devbox }}/.local/bin" init {{ .dotfilesRepo }} --apply --promptDefaults --force'
