devbox = "$HOME/devbox"
dotfileRepo = 'git@github.com:redbeardymcgee/dotfiles.git'
chezmoiInitHook = '\"sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "{{ .devbox }}/.local/bin" init redbeardymcgee --apply --ssh --promptDefaults --force\"'
