devbox = "$HOME/devbox"
dotfilesRepo = 'git@github.com:redbeardymcgee/dotfiles.git'
chezmoiInitHook = '"sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "{{ .devbox }}/.local/bin" init {{ .dorfilesRepo }} --apply --promptDefaults --force\"'
